spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/testDB?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.mingdev.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

#整合mybatis